name: test

on: [push]

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [21, lts/*, lts/-1]

    runs-on: ${{ matrix.os }}

    env:
      TZ: Asia/Tokyo

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm run test
